feat: add proper verify address modals everywhere
radixdlt/olympia-wallet pull request #197
Opened 2021-07-20 19:30 UTC by caleboller

This PR adds the verify address modal functionality to all relevant copy icons. When a hardware wallet is the active account, it will show the verify modal and cue the Ledger to verify the address before copying.

2021-07-20 20:49 UTC, staylorwr requested changes

2021-07-20 20:49 UTC, staylorwr commented on src/components/ClickToCopy.vue
> +    const hardwareAddress: Ref<string> = ref('')
This comes across as a code smell to me.  For nearly all cases, this component serves a single purpose of copying a string to the clipboard.   

With these new changes, the copy to clipboard component is now responsible for _always_ requesting the hardware address through the ipc, and then making it's own decisions about whether to emit an event or perform it's named responsibility.  

I'd advocate for either:

- writing a separate component named something like 'VerifyAndCopy' that contains this functionality, leaving the 'ClickToCopy' to handle other types of addresses
- add a new prop to this component that defines which function the component serves, ie:
```
props: {
  address: {
    type: String,
    required: true
  },
  action: {
    type: String,
    required: false,
    default: 'copy'
   }
}
```
In cases that you might be verifying, declare it as such w/ a `<click-to-copy action="verify"...>` so that it's clear what the intent of the component is.

2021-07-21 17:06 UTC, caleboller commented on src/components/ClickToCopy.vue
> +    const hardwareAddress: Ref<string> = ref('')
@staylorwr I've cleaned this up quite a bit and implemented one of your advised solutions:

- an optional `checkForHardwareAddress` can be sent to the component, defaulting to false.
- If that above option is set to true, the component will (at click time), fetch the hardware address from disk and compare, and then take the appropriate action - either instantly copying or showing the verify modal.

This implementation ensures we're not reading too frequently from disk, and makes the component friendly to use in list views. I should have caught this beforehand.

2021-07-21 17:53 UTC, staylorwr approved these changes

2021-07-21 17:54 UTC, merged