feat: On suspend, stop polling and send user home
radixdlt/olympia-wallet pull request #271
Opened 2021-08-04 13:09 UTC by caleboller

This Draft PR adds a small feature: When electron detects the host device is going into a suspended state (sleep), we send users currently viewing their wallet home, requiring them to enter their password to re-enter the wallet when the host device comes out of the suspended state.

This PR is blocked by a forthcoming change from @AbstractFruitFactory allowing us to stop all polling in the SDK at the same time.

2021-08-05 19:20 UTC, saminakh reviewed
These changes are neat! And good teaching material ✨ Was the async connection changes required to reconnect upon 'waking up'?

2021-08-05 19:20 UTC, saminakh commented on src/App.vue
> +      <suspense>
https://vueschool.io/articles/vuejs-tutorials/suspense-new-feature-in-vue-3/ reading about some of the suspense stuff here, this is a pretty nice pattern!

2021-08-05 19:20 UTC, saminakh commented on src/background.ts
> +    win.webContents.send('resetToHome')
👍

2021-08-05 23:55 UTC, caleboller commented on src/App.vue
> +      <suspense>
This was my first time using it as it's a recent addition to Vue 3! Pretty nice indeed!

2021-08-05 23:57 UTC, caleboller commented on src/background.ts
> +    win.webContents.send('resetToHome')
This `web.contents.send` function is how we send messages from the `main` process to the `render` process, you'll see elsewhere we use `ipcRenderer` to send messages from the `render` process to `main`.

2021-08-06 12:41 UTC, alexandreaco requested changes
Only blocking change here is to replace the "loading" string with the loading svg

2021-08-06 12:41 UTC, alexandreaco commented on src/background.ts
> +let win: BrowserWindow
Why did you need to declare this up top as a `let`?

2021-08-06 12:41 UTC, alexandreaco commented on src/App.vue
> +          <h1> Loading </h1>
Should we add the real loading icon here so we don't show an unstyled view to the end user?

2021-08-06 13:22 UTC, staylorwr approved these changes
I tested a fresh build of this locally and it works as expected 💯

2021-08-06 16:34 UTC, caleboller commented on src/background.ts
> +let win: BrowserWindow
@alexandreaco it's being defined in a function and thus previously was being scoped to that function. I need later access to it in a event callback, so I had to declare it up top.

2021-08-06 16:36 UTC, alexandreaco approved these changes
Thanks for adding the loader 👍

2021-08-06 16:44 UTC, merged