feat: add tooltip text upon hovering over Validator Name
radixdlt/olympia-wallet pull request #273
Opened 2021-08-04 17:25 UTC by SK-Sam

This PR warns the user about the Validator URL and displays the URL upon hovering its name via tooltip.

[Demo of Tooltip](https://www.loom.com/share/12f43902f9634d5b8bd4d8df7db0ba99)

2021-08-04 17:37 UTC, saminakh reviewed
These changes LGTM, and are working locally! I'm not sure I'm qualified yet to give a real approval though 🤔

2021-08-05 13:00 UTC, alexandreaco submitted a review, later dismissed
This tooltip works great! Let's turn this into a reusable component so it's a quicker addition next time. Happy to pair and show you what I mean :)

2021-08-12 18:25 UTC, saminakh reviewed
these changes are looking good to me! ✨

2021-08-12 19:23 UTC, caleboller requested changes

2021-08-12 19:23 UTC, caleboller commented on src/components/Tooltip.vue
> +  props: {
@SK-Sam Instead of using a prop here, you might want to consider using the [slot](https://vuejs.org/v2/guide/components-slots.html) instead. This would allow us to render not only strings in the tooltip component, but any html we like.

2021-08-12 19:30 UTC, saminakh commented on src/components/Tooltip.vue
> +  props: {
Is there a scenario where we'd want to put something other than a string in a tooltip? I suppose maybe being able to bold or italicize something with those html tags, is that the kind of scenario you were thinking of?

2021-08-12 21:42 UTC, SK-Sam commented on src/components/Tooltip.vue
> +  props: {
@caleboller cool feature, TIL. Added `slots` and removed `props` 😄

2021-08-19 17:00 UTC, staylorwr approved these changes

2021-08-19 17:01 UTC, merged