chore: Expose version and latest flag in client app
radixdlt/olympia-wallet pull request #373
Opened 2021-11-01 15:40 UTC by alexandreaco

2021-11-05 01:30 UTC, saminakh commented
@alexandreaco I can't actually tag you in a review because you were the author to this PR 😂 If you would be willing to leave a review (i dont think you can approve it though!) that would be lovely. If @caleboller or @staylorwr doesn't have the opportunity to review and can't give it an approval I can close and re-open the PR in my name so at least you have the ability to approve (assuming it's ready for approval).

2021-11-05 15:00 UTC, alexandreaco reviewed
Thanks @saminakh! The logic looks great, I just left a lot of vue-style nits 👩‍🏫

2021-11-05 15:00 UTC, alexandreaco commented on src/components/NetworkDisplay.vue
> +<template>
This component is only even called from the sidebar. Let's prepend the name with `Sidebar` to keep the components folder organized

2021-11-05 15:00 UTC, alexandreaco commented on src/components/NetworkDisplay.vue
> +      Version: </span> {{ versionNumber }} </p>
These small bits of text, "Version:" and "Network:", should be referenced through the `i18n` library

2021-11-05 15:00 UTC, alexandreaco commented on src/updater.ts
> +if (process.env.WEBPACK_DEV_SERVER_URL) {
Do we need to update .envrc?

2021-11-05 15:00 UTC, alexandreaco commented on src/updater.ts
> +  setUpdateIsAvailable(true)
🎉

2021-11-05 15:00 UTC, alexandreaco commented on src/updater.ts
> +  setUpdateIsAvailable(false)
👯

2021-11-05 15:00 UTC, alexandreaco commented on src/updater.ts
> +  autoUpdater.downloadUpdate()
So much cleaner!!

2021-11-05 16:57 UTC, saminakh commented on src/components/NetworkDisplay.vue
> +    const lowercaseNetwork: ComputedRef<string | undefined> = computed(() =>
Maybe it's time i stop doing radix work in vim....I wonder if VSCode has some baked-in functionality that would do some of this formatting for me 😅

2021-11-05 17:06 UTC, saminakh commented on src/updater.ts
> +if (process.env.WEBPACK_DEV_SERVER_URL) {
This should be good! It's used a couple of times in `background.ts`.

2021-11-08 19:31 UTC, staylorwr requested changes
I'm reading through these updates now but following your instructions for dev updates I receive the following crash on booting the app with `yarn electron:serve`:
<img width="421" alt="Screen Shot 2021-11-08 at 2 30 15 PM" src="https://user-images.githubusercontent.com/2738409/140805648-e752d392-76aa-4fb8-9172-4884ffff23bb.png">

2021-11-08 19:32 UTC, staylorwr commented on README.md
>  ### Customize configuration
Can you include instructions for setting up the dev environment files to the top of the instructions like so:

```
yarn
cp .envrc{.sample,}
cp dev-app-update.yml{.sample,}
```
under the project setup?

2021-11-08 19:47 UTC, staylorwr requested changes
A real review now :) I'm unable to test the update functionality because of the crash.  And I'd love to swap the generic electron icon with the radix logo.

2021-11-08 19:47 UTC, staylorwr commented on src/views/Wallet/WalletSidebarDefault.vue
> +    cursor-pointer mb-2 px-5" @click="setState(true)">
🤔 can you keep this to a single line or break out the lines by attr? ie:

```
<div 
  class="
  @click="
>

2021-11-08 19:47 UTC, staylorwr commented on src/components/SidebarNetworkDisplay.vue
> +    getVersionNumber().then((res) => { versionNumber.value = res })
This is sort a business-logic like request being fired off through a `setup` function that could rerender.  What do you think about this logic (and these values) living in the `useWallet` composable?

2021-11-08 19:47 UTC, staylorwr commented on src/menu.ts
> -import { app, Menu, MenuItem } from 'electron'
👋🏼 👍🏼

2021-11-08 21:07 UTC, saminakh commented
@staylorwr did you update `dev-app-update.yml` to have a legitimate token? I reproduced this error by leaving in `my-github-token` as the value.

Thank you for the thorough feedback! I will clean this up 🙇

2021-11-08 23:11 UTC, saminakh commented on src/components/SidebarNetworkDisplay.vue
> +    getVersionNumber().then((res) => { versionNumber.value = res })
I think that makes sense! Fixed 👍

2021-11-09 20:02 UTC, staylorwr approved these changes
💯 I was able to build a production build and test the upgrade process locally.  Looks great Samina!

2021-11-10 17:48 UTC, merged