chore: throw warning msg upon any transaction where total XRD balance…
radixdlt/olympia-wallet pull request #374
Opened 2021-11-04 23:27 UTC by SK-Sam

This PR will throw a warning to the User to let them know upon this transaction, their total XRD balance will be < 10 XRD. This message applies to Staking and Sending Tokens, but not Unstaking.

Since we're hitting the API to get User's Total XRD Balance in the WalletConfirmTransactionModal, would it be helpful to display the User's total XRD post-transaction as well? Another row that says...`Remaining XRD After Transaction: ` `1,0004.068 XRD`? something like this? Would like your thoughts on this @alexandreaco @saminakh 

[Demo for Sending/Staking](https://www.loom.com/share/a91f49fb5c0d4e178a5c51edd8cc078d)
[Demo for Unstaking & the lack of this warning message](https://www.loom.com/share/b2823102ee4f4b9e94f16625a5180eaf)

2021-11-05 14:47 UTC, alexandreaco requested changes
Thanks for the inline docs and thorough PR comments! I left some changes to clean this up. Great first pass :)

2021-11-05 14:47 UTC, alexandreaco commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +        radix.ledger.stakesForAddress(account.address),
We don't need stakesForAddress and unstakesForAddress here so we can simplify this subscription.

```js
switchMap(() => radix.activeAccount),
mergeMap((account) => radix.ledger.tokenBalancesForAddress(account.address))
```

2021-11-05 14:47 UTC, alexandreaco commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +      subs.unsubscribe()
Good thinking, we always want to unsubscribe. However, this view isn't a route view, it's a nested component. So here, let's use `onUnmounted()` instead of `onBeforeRouteLeave()`

2021-11-05 14:47 UTC, alexandreaco commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +    xrdRemainderBalanceAboveTen (): boolean {
Do you mean "below" ten? :) 

Also, please move this to a computedRef within setup() to keep with the composition api spec.

2021-11-05 16:01 UTC, SK-Sam commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +    xrdRemainderBalanceAboveTen (): boolean {
I definitely meant `below` and my results are making much more sense now w/ the name change 😸

2021-11-05 16:06 UTC, SK-Sam commented
🙇 🙇 changed up to your specs, thanks for the kind review @alexandreaco ! Didn't realize `ComputedRef` was part of the composition api.

2021-11-05 16:57 UTC, alexandreaco commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +      mergeMap((account) => forkJoin([
You don't need the forkJoin here because we only have one sub now :)

2021-11-05 16:57 UTC, alexandreaco commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +    ).subscribe(([balances]) => {
When you remove forkJoin you'll also take this out of the array deconstructor

2021-11-05 16:57 UTC, alexandreaco commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +        <div class="pr-6" v-if="xrdRemainderBalanceBelowTen">
I'm going to leave the same style nit here that I put on samina's PR so we can be more consistent moving forward. 

When you have a DOM element with a vue attr, you want to break up that div onto separate lines. v-if and other templating attrs should always come first

```jsx
<div
  v-if="xrdRemainderBalanceBelowTen"
  class="pr-6"
>
  <span class="text-rRed text-md">
    <b>{{ $t('transaction.warningTitle') }}:</b> {{ $t('transaction.lessThanTenXRDBalanceWarning')}}
  </span>
</div>
```

2021-11-05 19:28 UTC, SK-Sam commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +        <div class="pr-6" v-if="xrdRemainderBalanceBelowTen">
good to know 👍

2021-11-05 20:57 UTC, saminakh reviewed
The warning looks good and the logic looks sound! I did notice one case that may have slipped through the cracks: when a user has less than 10 XRD to begin with, and makes a transaction that keeps their balance below 10 XRD. I think no warning is supposed to show in this case, b/c at that point _every_ transaction will cause them to be below 10 because they were below 10 to begin with!
<img width="1197" alt="Screen Shot 2021-11-05 at 2 52 37 PM" src="https://user-images.githubusercontent.com/8646176/140577520-7877209c-5219-4857-879d-f89512f31e86.png">

2021-11-05 20:57 UTC, saminakh commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +    const zero = Amount.fromUnsafe(0)._unsafeUnwrap()
👍 this is handy!

2021-11-05 21:32 UTC, SK-Sam commented
> The warning looks good and the logic looks sound! I did notice one case that may have slipped through the cracks: when a user has less than 10 XRD to begin with, and makes a transaction that keeps their balance below 10 XRD. I think no warning is supposed to show in this case, b/c at that point _every_ transaction will cause them to be below 10 because they were below 10 to begin with! <img alt="Screen Shot 2021-11-05 at 2 52 37 PM" width="1197" src="https://user-images.githubusercontent.com/8646176/140577520-7877209c-5219-4857-879d-f89512f31e86.png">

this may be true, i probably wouldn't want someone telling me every transaction how close to 0 i am 😢

2021-11-09 15:28 UTC, SK-Sam commented
> The warning looks good and the logic looks sound! I did notice one case that may have slipped through the cracks: when a user has less than 10 XRD to begin with, and makes a transaction that keeps their balance below 10 XRD. I think no warning is supposed to show in this case, b/c at that point _every_ transaction will cause them to be below 10 because they were below 10 to begin with! <img alt="Screen Shot 2021-11-05 at 2 52 37 PM" width="1197" src="https://user-images.githubusercontent.com/8646176/140577520-7877209c-5219-4857-879d-f89512f31e86.png">

Well hmm, thought about it over the weekend. if the main point of the warning is to warn the user that there's an underlying fee to transactions, should this warning be thrown even when under 10 XRD? 🤔 💭 it mayyy be safe to assume the user is new to the Radix platform?

2021-11-30 12:57 UTC, alexandreaco commented
Hey @SK-Sam, I checked the original Linear story and Matt would like the warning to **not** appear when a user has less than 10 xrd to begin with
> Let's just show a bright red warning in the confirmation modal if a user is ever about the submit a TX that would take their XRD balance from > 10 XRD to < 10 XRD.

https://linear.app/township/issue/RDX-252/add-warning-message-when-about-to-send-all-or-nearly-all-xrd

2021-11-30 14:46 UTC, alexandreaco commented
@saminakh Can you please re-review this? I made the last update to not show the warning when users have < 10 xrd to begin with

2021-11-30 18:10 UTC, saminakh approved these changes
Left one Q, but leaving an approval to speed up the merging process in case my comment isn't applicable! The case itself LGTM!

2021-11-30 18:10 UTC, saminakh commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +      } else if (totalXRD.value && Number(totalXRD.value) < Math.pow(10, 19)) {
My only thought here is, should this be the top case? The case itself looks correct though!

2021-12-01 12:57 UTC, alexandreaco commented on src/views/Wallet/WalletConfirmTransactionModal.vue
> +      } else if (totalXRD.value && Number(totalXRD.value) < Math.pow(10, 19)) {
You're right, thank you! Updated :)

2021-12-01 12:57 UTC, alexandreaco approved these changes

2021-12-01 12:57 UTC, merged