feat: Allow users to enter 12, 18 and 24 phrase mnemonics
radixdlt/olympia-wallet pull request #375
Opened 2021-11-05 14:24 UTC by alexandreaco

2021-11-09 22:16 UTC, saminakh requested changes
👋 I tested wallet creation and restoration and those look good! I did note one spot that may have been missed--revealing the seed phrase while already authenticated:
<img width="1192" alt="Screen Shot 2021-11-09 at 3 09 23 PM" src="https://user-images.githubusercontent.com/8646176/141013539-305ff352-3a0e-485a-9cae-025552056a39.png">
It looks like the seed phrase is correct but the count in the copy is still assuming 12.

I'll do a proper code review after this!

2021-11-09 23:03 UTC, saminakh reviewed
Left some Q's and comments!

2021-11-09 23:03 UTC, saminakh commented on src/views/RestoreWallet/RestoreWalletEnterMnemonic.vue
> +    const strengthOptions: AppSelectOptionT[] = [
This part (and some other code in this page) feels kind of repetitive with code in `CreateWalletViewMnemonic.vue`, and potentially some of the code in the 'reveal seed phrase' view too. Maybe it'd be worth breaking some of this into a mnemonic helper? Some of the logic to build the select or something? Just a thought though! You're the vue expert!

2021-11-19 16:06 UTC, staylorwr requested changes
https://www.loom.com/share/c441ba9c9eca405f9c4f1041515e4702

@alexandreaco functionally this looks great.  

In the loom above, could you update the padding or layout of the page so that:
- toggling show / hide state of the 'change seed phase length' ui doesn't change heights?  Maybe just set a fixed height of the parent element so it doesn't change the page layout?
- update the vertical padding of the 24-word phrase so it doesn't push the button below the fold.

2021-11-29 15:03 UTC, alexandreaco commented
Thanks for the reviews!

@staylorwr Updated padding on create https://www.loom.com/share/0ace9507761f438081fb044633035cee
@saminak Added the UI missing work for viewing a user's current mnemonic
<img width="1312" alt="Screen Shot 2021-11-29 at 9 59 04 AM" src="https://user-images.githubusercontent.com/4480888/143890879-52701f6b-e45d-43e4-bd58-adc21a1a4088.png">

2021-11-30 18:18 UTC, staylorwr approved these changes
🎁

2021-11-30 18:31 UTC, saminakh requested changes
It looks like the `mnemonicDisclaimer` in `src/text/index.ts` still has the '12' hardcoded in it, so on the `SettingsRevealMnemonic.vue` page it's not always displaying the right count in that copy.

2021-12-01 13:08 UTC, alexandreaco commented on src/components/AppSelect.vue
> +    <ul
Unfortunately, that's not a feature that comes out-of-the-box with vue. Alpine is pretty incredible for including that as a default. I'll bring this up to the radix team when then QA it so see if we should invest a bit more time to set this up

2021-12-01 13:19 UTC, alexandreaco commented
@saminakh Fixed, thank you for your eagle eyes 🙇‍♀️

2021-12-01 18:46 UTC, saminakh requested changes
one last linter shenanigan, sorry alex :(

2021-12-01 18:46 UTC, saminakh commented on src/helpers/mnemonic.ts
> +]
```
 ERROR  Failed to compile with 1 error                                                                                                                                                                           11:45:08 AM

 error  in ./src/helpers/mnemonic.ts

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/samina/Documents/radix/olympia-wallet/src/helpers/mnemonic.ts
  17:2  error  Newline required at end of file but not found  eol-last

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```
  😭 This linter has no chill

2021-12-02 16:00 UTC, alexandreaco commented
That newline error 🤦‍♀️ I see the updated copy when I run it, can you confirm one more time?

<img width="1312" alt="Screen Shot 2021-12-02 at 10 59 38 AM" src="https://user-images.githubusercontent.com/4480888/144457567-2ed4fb38-5828-4f99-bd7b-a61bee04fff4.png">

2021-12-02 19:33 UTC, saminakh approved these changes
🎉 LGTM! Thank you for all the fixes!

2021-12-02 19:36 UTC, merged