chore: add indication to current stakes list
radixdlt/olympia-wallet pull request #377
Opened 2021-11-15 13:09 UTC by SK-Sam

[Demo](https://www.loom.com/share/3bb6bef1a1fa4bdab4a01a1a529034a9)

This PR gets the Top 100 Validators, and checks against User's current stake positions. If any positions are outside of the Top 100 Validators, we will indicate by showing a `no emissions` text on validator.

Demo video mocks a Top 28 Validators list, and I want to show that by changing the value to 27, the 28th Validator will show the `no emissions` text.

2021-11-16 21:48 UTC, saminakh reviewed
I think the code overall looks good! I think it would be a nice-to-have if there wasn't a delay between the page rendering and the app fetching the top 100 list/determining the 'no emissions' value. When i click on the staking/unstaking view, it indicates the few validators i have stakes w/ are 'no emissions', but then after a few moments the indicator disappears. Would swapping the default help with this? Also, would it make sense to subscribe to the top 100 list earlier in the flow? (Maybe when the app boots up, rather than when you first open the staking/unstaking page?) I'm not sure if that's doable, perhaps @alexandreaco or @staylorwr would have suggestions here.

2021-11-19 15:56 UTC, staylorwr requested changes

2021-11-19 15:56 UTC, staylorwr commented on src/views/Wallet/WalletStaking.vue
> +    })
@SK-Sam this looks like the right logic but it seems we have a little cleaning up to do here.  Can you move this validator logic into the `useStaking` composable? 

We should also only have a single call to `useStaking` in the setup of this function, as we're currently calling it twice, and generating two sets of `radix.stakingPositions` and `radix.unstakingPositions` subscriptions but only unsubscribing from a single one.   (line 158 and line 183).  

Once you have all of the subscription logic in `useStaking`, could you also take a look at moving the reference to the global list of top 100 validators outside of the `useStaking` function definition?   `useWallet` and `useTransactions` have some examples of defining the reference outside of the function definition and then passing those const references.  (This allows for the reference to exist outside of the lifecycle of the composable and the component that called the composable, making them effectively 'global' values that can be referenced multiple times without losing context, like the main `radix` instance from `useWallet`)

Otherwise this looks great, sorry that we still have some bad examples of non-composable logic floating around.  Thank you @SK-Sam!

2021-11-30 15:49 UTC, alexandreaco commented on src/views/Wallet/WalletStaking.vue
> +    })
I went in and cleaned this up. Can you give it another review?

2021-11-30 18:17 UTC, staylorwr approved these changes

2021-12-01 12:58 UTC, merged