feat: Users can hide other token types from view
radixdlt/olympia-wallet pull request #379
Opened 2021-11-18 17:38 UTC by alexandreaco

2021-11-18 20:43 UTC, caleboller requested changes
Hey Alex! I did a QA review of this. This is looking pretty nice! I'd like to request the following changes:

- [x]  When on the Tokens setting page, hovering over the `unhide balance` button, the icon should transition to the visible eye icon.
- [x]  The Unhide Balance modal should have appropriate explainer copy. Do we need to get that from Matt?
- [x]  We need a better state for the Tokens setting page when no balances are hidden. I'll speak to Baxter about this.
- [x]  I think we also need to land on exactly how we want to refer to these. We use `Balance` in most places, but use `Tokens` in the settings nav bar. Let's use `Balances` everywhere for now.

2021-11-18 20:51 UTC, alexandreaco commented
@caleboller thanks for the quick feedback. Here's the copy we have for unhide balances. I can update this `Are you sure you want to unhide this eMunie balance?`

2021-12-01 14:07 UTC, alexandreaco commented on src/views/Settings/SettingsTokens.vue
> +        mergeMap((account: AccountT) => radix.ledger.tokenBalancesForAddress(account.address))
Good call here. I needed to do a little more massaging to ensure `activeAccount` was loaded before the view, but this new setup removed an extra api call 🙂

2021-12-02 16:07 UTC, caleboller approved these changes

2021-12-02 16:07 UTC, merged