Samina/rdx 282 put up warning if caps lock is set on
radixdlt/olympia-wallet pull request #391
Opened 2021-11-24 01:02 UTC by saminakh

This PR introduces a `PasswordField` that extends the existing `FormField` and adds some additional logic to detect if either capslock is pushed, or if the input has caps enabled (to handle cases where a user enables caps lock in a separate window and then returns to the wallet).

https://www.loom.com/share/a070f7e403b14641a5e7f0b7730dda4d

2021-11-29 15:05 UTC, SK-Sam approved these changes
Works fine on my side 😄 I have tried all sorts of approaches such as enabling Caps in the middle of input, clicking out of text box + activating Caps in the middle of input, etc. Everything checks out, thank you!

2021-11-29 15:05 UTC, SK-Sam commented on src/views/Home/HomeEnterPasscode.vue
> +        <PasswordField
👏 awesome!

2021-11-29 15:22 UTC, alexandreaco requested changes
Works great! We missed one screen for when a user is creating a password when creating or restoring a wallet
<img width="1312" alt="Screen Shot 2021-11-29 at 10 19 52 AM" src="https://user-images.githubusercontent.com/4480888/143894796-bb99392b-de48-4e54-bd8e-4cd95c66a960.png">

2021-11-29 15:22 UTC, alexandreaco commented on src/views/Home/HomeEnterPasscode.vue
> +        <PasswordField
💯

2021-11-29 19:52 UTC, saminakh commented
Thank you for the eyes everyone! I added in that missing view, lemme know if it's GTG now!

2021-11-30 14:41 UTC, staylorwr approved these changes

2021-11-30 14:41 UTC, staylorwr commented on src/components/PasswordField.vue
> +      v-on:keydown.caps-lock="checkCapsLock"
💯 this is clever, I forgot about the event modifiers.

2021-11-30 18:36 UTC, saminakh commented on src/components/PasswordField.vue
> +      v-on:keyup="checkCapsLock"
👍 polish implemented!

2021-11-30 18:37 UTC, merged