chore: change vocabulary from node to gateway
radixdlt/olympia-wallet pull request #402
Opened 2021-12-06 14:56 UTC by SK-Sam

This PR changes all instances of `node` to `gateway`. Settings page is mostly affected by this change, along with possible `node` based errors.

![Screen Shot 2021-12-06 at 9 45 14 AM](https://user-images.githubusercontent.com/10618376/144868232-0ea0a41a-0c58-4594-872a-1fd6600d8382.png)

2021-12-06 14:59 UTC, SK-Sam commented
Before: 
![Screen Shot 2021-12-06 at 9 31 21 AM](https://user-images.githubusercontent.com/10618376/144868792-4b60e774-b228-4ab9-8a38-b86d4ffd1e5e.png)

2021-12-08 14:31 UTC, caleboller requested changes
Hey @SK-Sam - on the surface this looks 💯 . Thank you for the changes!

However, I want to encourage you to always leave code better than you find it. The copy in `src/views/Settings/index.vue` hasn't been internationalized - it was probably implemented under duress - as you're touching this file, would you mind to fully internationalize the tab titles?

Thank you!

2021-12-08 15:45 UTC, SK-Sam commented
> Hey @SK-Sam - on the surface this looks 💯 . Thank you for the changes!
> 
> However, I want to encourage you to always leave code better than you find it. The copy in `src/views/Settings/index.vue` hasn't been internationalized - it was probably implemented under duress - as you're touching this file, would you mind to fully internationalize the tab titles?
> 
> Thank you!

Thanks for pushing for top notch work 😄 . I've internationalized tabs, and have adjusted our i18n file to use Gateway instead of Node as well. @caleboller

2021-12-09 18:55 UTC, caleboller approved these changes

2021-12-09 18:55 UTC, merged