WIP: Samina/rdx 315 improved error handling
radixdlt/olympia-wallet pull request #410
Opened 2021-12-21 01:10 UTC by saminakh

Todo:
- [ ] NetworkNotSupportedError
- [ ] InvalidTokenRRIError
- [ ] InvalidAccountAddressError
- [ ] InvalidValidatorAddressError
- [ ] NotEnoughNativeTokensForFeesError
- [ ] NotEnoughTokensForTransferError
- [ ] NotEnoughTokensForStakeError
- [ ] NotEnoughTokensForUnstakeError
- [ ] BelowMinimumStakeError
- [ ] CannotStakeError
- [ ] MessageTooLongError

Examples:
<img width="1199" alt="Screen Shot 2021-12-20 at 5 59 35 PM" src="https://user-images.githubusercontent.com/8646176/146853811-a539a010-820d-458f-a9bb-4e434c9ed6b9.png">

<img width="1297" alt="Screen Shot 2021-12-20 at 6 10 33 PM" src="https://user-images.githubusercontent.com/8646176/146853838-244b3c72-7280-42d9-b1b0-efb99b5da77a.png">

2022-01-05 14:19 UTC, alexandreaco commented
I can't leave a review because it's still a WIP branch, but here's some feedback :) @saminakh 

1. https://github.com/radixdlt/olympia-wallet/pull/410/files#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0R6-R13 I don't think we'll ever show the transaction building error because isApiError will return true first
2. https://github.com/radixdlt/olympia-wallet/pull/410/files#diff-7deb4a2ae75ee9c0d8e9807092fd413c257fae59ca15a80bb16276daf099577eL244-R244 Typo, we lost a space between words
3. I wonder if we want the copy to say "Unknown Api Error" or something more confident like "Received Api Error" when we don't have friendly text to show. <img width="1312" alt="Screen Shot 2022-01-05 at 9 13 00 AM" src="https://user-images.githubusercontent.com/4480888/148231560-4664c632-768d-411f-8faa-2f758cc27f28.png"> 
4. I'm having trouble creating a "not enough XRD to cover fee" error. This may be an issue with the Api <img width="1440" alt="Screen Shot 2022-01-05 at 9 14 53 AM" src="https://user-images.githubusercontent.com/4480888/148231863-cf41db32-e831-47a5-96a7-9c8c5033998d.png"> 
5. For `NotEnoughTokensForUnstakeError`, we should check with Radix to see if we need to present both of those messages to the user

2022-01-05 22:55 UTC, saminakh commented
Thank you for the feedback @alexandreaco !
1. Todo
2. Fixed!
3. I think that's a good idea! I changed it!
4. I did manage to reproduce this, it appears that the API only sends this error if you're sending NON-native tokens and you don't have enough native tokens to cover the transaction fee. There doesn't appear to be a corresponding error for if you're sending native tokens though and don't have enough to cover the transaction fee. Should we tell radix and recommend they add an api error for that?
5. Todo

2022-01-07 13:21 UTC, alexandreaco requested changes
Thanks for all of this work! 🙇‍♀️  I left a few notes about small nits and minor updates

2022-01-07 13:21 UTC, alexandreaco commented on src/components/ErrorModalApi.vue
> +      errorMsg = 'Unexpected Error'
Let's make sure we're using the i18n text file for these bits of text :)

2022-01-07 13:21 UTC, alexandreaco commented on src/components/ErrorModalApi.vue
> +      errorMsg = t(`apiErrors.${type}`, { minimum: displayMinimum })
nit: I don't think you need to template the string `apiErrors.${type}` because we always know the type is `BelowMinimumStakeError`. Nice use of custom values in the i18n call!

2022-01-07 13:21 UTC, alexandreaco commented on src/components/ErrorModalApi.vue
> +      errorMsg = t(`apiErrors.${type}`)
Would we really ever get to this clause? Maybe you can reverse your conditionals and just leave a single "else"

if (requested <= add(staked, pending))
  // show pending error
else 
  // show default error

2022-01-07 13:21 UTC, alexandreaco commented on src/composables/useTransactions.ts
> +      completion.subscribe(handleTransactionCompleted, errorHandler)
neat! i didn't know you could pass multiple functions into subscribe

2022-01-07 13:21 UTC, alexandreaco commented on src/composables/useWallet.ts
> +    persistNodeUrl('https://stokenet-gateway.radixdlt.com')
I think you'll have rebase conflicts because I made these strings a const. sorry!

2022-01-07 13:21 UTC, alexandreaco commented on src/text/index.ts
> +      NetworkNotSupportedError: 'The network selected is not valid.',
We can remove some of these errors. We should only show custom errors for the following codes

InvalidAccountAddressError
InvalidValidatorAddressError
NotEnoughNativeTokensForFeesError
NotEnoughTokensForTransferError
NotEnoughTokensForStakeError
NotEnoughTokensForUnstakeError
BelowMinimumStakeError
CannotStakeError
MessageTooLongError

2022-01-07 13:21 UTC, alexandreaco commented on src/composables/useErrors.ts
> +  'BelowMinimumStakeError',
We also need to remove the inline check for 90xrd

2022-01-07 13:21 UTC, alexandreaco commented on src/composables/useErrors.ts
> +  'MessageTooLongError'
We also need to remove the inline check for when messages are longer than 160 characters

2022-01-07 18:35 UTC, saminakh commented on src/composables/useWallet.ts
> +    persistNodeUrl('https://stokenet-gateway.radixdlt.com')
No worries! Rebased 👍

2022-01-07 18:41 UTC, saminakh commented on src/components/ErrorModalApi.vue
> +      errorMsg = t(`apiErrors.${type}`)
Oh! I think i named the error messages confusingly. I'll change this to make it clearer!

2022-01-07 20:21 UTC, saminakh commented on src/components/ErrorModalApi.vue
> +      errorMsg = 'Unexpected Error'
👍

2022-01-07 20:22 UTC, saminakh commented on src/components/ErrorModalApi.vue
> +      errorMsg = t(`apiErrors.${type}`, { minimum: displayMinimum })
Yeah good point! I did this in another spot too so I'll change 'em both!

2022-01-07 20:54 UTC, saminakh commented on src/composables/useTransactions.ts
> +      completion.subscribe(handleTransactionCompleted, errorHandler)
I didn't either! someone from radix had a code example in the channel 😄

2022-01-07 20:58 UTC, saminakh commented on src/text/index.ts
> +      NetworkNotSupportedError: 'The network selected is not valid.',
👍 totally forgot to remove these cases, thanks for the reminder!

2022-01-07 21:01 UTC, saminakh commented on src/composables/useErrors.ts
> +  'BelowMinimumStakeError',
I should have asked about the inline validations, that was silly of me not to. I thought maybe these modals would just be backups if the inline checks failed? But that was a silly assumption in retrospect 😬

2022-01-07 21:38 UTC, saminakh commented on src/composables/useErrors.ts
> +  'MessageTooLongError'
👍

2022-01-07 22:14 UTC, saminakh commented
@alexandreaco for title/copy change for the error modals, I went with:
- Cannot Create Transaction
- Cannot Complete Stake
- Cannot Complete Unstake
Do those sound reasonable?

2022-01-10 11:38 UTC, alexandreaco requested changes
The new error modals look great. Thanks for adding in the titles :) 

I left a few notes in the PR that we should cleanup before merging. 

Lastly, can you add some horizontal padding to this sentence so we don't have an orphaned word on the second line? In the screenshot I tried px-12 and it looks nicer.
<img width="1268" alt="Screen Shot 2022-01-10 at 6 29 58 AM" src="https://user-images.githubusercontent.com/4480888/148759882-f9093429-3285-44bc-8518-8f5323da8bea.png">

2022-01-10 11:38 UTC, alexandreaco commented on src/App.vue
> +          v-if="isApiError"
`isApiError` returns true if `latest.error?.details?.type` exists. This means that we'll never get to the subsequent else-if statements that are checking for that type to be a specific string. Maybe you intended to import `isApiError` from `useErrors`?

2022-01-10 11:38 UTC, alexandreaco commented on src/components/ErrorModalApi.vue
> +        <p class="mb-2">Please contact support at <a class="text-rBlue"
Can we add these phrases to the text.ts file?

2022-01-10 11:38 UTC, alexandreaco commented on src/text/index.ts
> +        message: 'The recipient Radix address specified is not valid.',
👍 This nesting is really easy to follow and documents the flow well. Great idea

2022-01-10 11:38 UTC, alexandreaco commented on src/views/Wallet/WalletTransaction.vue
> -                      :rules="{
I'm seeing a runtime error now that rules is undefined. Can you set rules to an empty object instead?

2022-01-10 17:09 UTC, saminakh commented on src/App.vue
> +          v-if="isApiError"
Ahh I see what's confusing here. The flow should be: check that `latest.error.details.type` exists. If yes: show api error modal, where we look at the type (and if the type is found, show that simplified error modal for that type, otherwise, show the detailed error modal w/ the trace id). If `latest.error.details.type` doesn't exist, _then_ we think it's not an API error and show one of the other modals instead.

So I think the problem here is, is there a better way to check if it's an API error or not? I can look a little more closely at the error and see if there's a nicer way to do this.

2022-01-10 17:10 UTC, saminakh commented on src/components/ErrorModalApi.vue
> +        <p class="mb-2">Please contact support at <a class="text-rBlue"
Yeah! Should i just break the string into two chunks surrounding the link?

2022-01-10 17:10 UTC, saminakh commented on src/text/index.ts
> +        message: 'The recipient Radix address specified is not valid.',
😄

2022-01-10 17:11 UTC, saminakh commented on src/views/Wallet/WalletTransaction.vue
> -                      :rules="{
Good catch! Sorry about that, I'll go and fix it!

2022-01-10 19:21 UTC, saminakh commented on src/components/ErrorModalApi.vue
> +        <p class="mb-2">Please contact support at <a class="text-rBlue"
(I ended up just doing that!)

2022-01-10 19:47 UTC, saminakh commented on src/App.vue
> +          v-if="isApiError"
Ok! Here's what I did. I:
- updated where we handle the api errors to include a `type` flag of 'api' before adding it to the list of errors for the app. This 1) is probably a better way of checking if the error is an api type or a general app error, and 2) makes the logic a little more clear
- renamed the `isApiError` --> `isKnownApiError`, to make the purpose of that function more clear

2022-01-10 20:04 UTC, alexandreaco approved these changes
💯

2022-01-10 20:04 UTC, alexandreaco commented on src/App.vue
> +          v-if="isApiError"
Thanks, this makes much more sense now!

2022-01-10 20:06 UTC, merged