chore: ping network every 10 seconds to check connectivity
radixdlt/olympia-wallet pull request #421
Opened 2022-01-19 14:37 UTC by alexandreaco

<img width="1312" alt="Screen Shot 2022-01-19 at 9 37 22 AM" src="https://user-images.githubusercontent.com/4480888/150152223-240845b9-a560-484f-887b-aec4aaa70295.png">

2022-01-19 17:59 UTC, staylorwr requested changes
Thanks for this feature @alexandreaco!  It looks like this also highlights a
  regression in the refactor or error handling work where we're no longer able
  to visit the settings tabs to change the gateway / network without internet
  access.

  Can you work on that functionality in this PR (or document next steps towards bring that functionality back for the team)?

2022-01-20 17:09 UTC, staylorwr approved these changes

2022-01-20 19:43 UTC, saminakh approved these changes
These changes LGTM and are working locally! Left a few thoughts for the future!

2022-01-20 19:43 UTC, saminakh commented on src/App.vue
> +          setError(new Error(t('errors.networkError')))
👍

2022-01-20 19:43 UTC, saminakh commented on src/views/Home/HomeEnterPasscode.vue
> +        if (error.message === 'network timeout') {
Should we set an error here to show a modal letting the user know why they're getting sent straight to the node settings page? Perhaps a nice-to-have in the future?

2022-01-20 19:43 UTC, saminakh commented on src/views/Home/HomeEnterPasscode.vue
> +        if (error.message === 'network timeout') {
On a similar note, the gateway change modal is a little wonky (`cancel` button not fitting). We should make an issue for this!
<img width="602" alt="Screen Shot 2022-01-20 at 12 42 28 PM" src="https://user-images.githubusercontent.com/8646176/150410724-39b50810-e3d7-4926-baef-0cdf024bd746.png">

2022-01-20 19:49 UTC, SK-Sam approved these changes

2022-01-20 19:54 UTC, merged