chore: add ledger decrypt message modal
radixdlt/olympia-wallet pull request #443
Opened 2022-02-08 04:46 UTC by saminakh

This PR updates the wallet history page to include a modal when:
1) the current active account is a hardware account, and
2) when the wallet is waiting on the hardware ledger to confirm decryption

See loom demo:
https://www.loom.com/share/526c0941717d46adb1c7df48948f132e

2022-02-08 18:26 UTC, staylorwr requested changes

2022-02-08 18:26 UTC, staylorwr commented on src/views/Wallet/WalletHistory.vue
> +    watch((activeAccount), () => {
You shouldn't need two `watch` statements here, both are setting the `isHardwareAccount` value.

2022-02-08 18:43 UTC, saminakh commented on src/views/Wallet/WalletHistory.vue
> +    watch((activeAccount), () => {
Doh! This was supposed to be watching the `hardwareAccount` value 🤦 I lost this logic when rebasing on top of main because i had forgotten to pull it down initially. Thank you for the catch!

2022-02-08 18:48 UTC, saminakh commented on src/views/Wallet/WalletHistory.vue
> +    watch((activeAccount), () => {
oh nevermind, i do have one watching `activeAccount` and one watching `hardwareAccount`. I'm tracking both here because when this component is first setup (when `useHistory` is first called) `hardwareAccount` is sometimes null. Is there a different way I can check to see if the user's currently viewing the history of a hardware account without watching both of these values?

2022-02-10 12:39 UTC, alexandreaco commented on src/views/Wallet/WalletHistory.vue
> +    const shouldShowDecryptModal: ComputedRef<boolean> = computed(() => {
minor nit: you can make this a 1 liner with an implicit return `const shouldShowDecryptModal: ComputedRef<boolean> = computed(() => isHardwareAccount.value && isDecrypting.value)`

2022-02-10 12:42 UTC, alexandreaco commented on src/views/Wallet/WalletHistory.vue
> +    watch((activeAccount), () => {
I'm looking at this more and it seems like you're trying to do two different things.

1. `isHardwareAccount` is true when the active account is the hardware account. This can just be a computed property.
2. you reset history when the active account changes. This is a side effect and should live in a watch()

2022-02-10 23:50 UTC, saminakh commented on src/views/Wallet/WalletHistory.vue
> +    watch((activeAccount), () => {
@alexandreaco @staylorwr thank you for the help here! This should be cleaned up now! watching `hardwareAccount` did not appear to be necessary after all :D

2022-02-10 23:51 UTC, saminakh commented on src/views/Wallet/WalletHistory.vue
> +    const shouldShowDecryptModal: ComputedRef<boolean> = computed(() => {
i took it a step further and just put the logic for computing `isHardwareAccount` right inside `shouldShowDecryptModal`!

2022-02-10 23:52 UTC, saminakh commented
@alexandreaco @staylorwr could you look at this one last time? I cleaned it up after alex walked me through some changes after sprint planning!

2022-02-11 11:56 UTC, alexandreaco approved these changes
Thanks for the updates!

2022-02-11 11:56 UTC, alexandreaco commented on src/views/Wallet/WalletHistory.vue
> +    const shouldShowDecryptModal: ComputedRef<boolean> = computed(() =>
👍

2022-02-14 18:35 UTC, staylorwr approved these changes

2022-02-14 18:52 UTC, merged