Perry/rdx 349 fix staking for prematurely displays
radixdlt/olympia-wallet pull request #468
Opened 2022-03-02 22:49 UTC by P-v-R

[Extension of this pull request ](https://github.com/radixdlt/olympia-wallet/pull/466)

We found an additional premature form field error popping up when a user clicks into either 'address' or 'amount', clicking out of the form field component entirely causes an error message to appear even when `add/reduce stake` is clicked. An easy way around this was to disable validation on blur - and as an extra level of protection, add `validateOnInput = true` to the address field.

📸 - *notice at end I delete a character from the address and the error message appears*
![radixValidFix](https://user-images.githubusercontent.com/72633467/156462844-4ce086e4-25f9-4abe-9742-51cb230b84ca.gif)

2022-03-02 22:50 UTC, P-v-R commented
fixing merge conflict now

2022-03-04 16:53 UTC, alexandreaco requested changes

2022-03-04 16:53 UTC, alexandreaco commented on src/views/Wallet/WalletStaking.vue
> +              :validateOnBlur="false"
Validations are so tricky! Unfortunately not validating on blur introduces more bugs. If we are not validating on blur, then the warnings don't appear. But the form is also not being validated. That means that the submit button will not be enabled unless the user goes back and manually inputs text into both fields. See this loom where I press "add stake", enter an amount, and attempt to submit the form https://www.loom.com/share/af3bcae11e7140bd9650d0c60ef89be1

This is a case where representing the problem in a [DDD style](https://martinfowler.com/bliki/GivenWhenThen.html) can help illuminate the problem. Here is the first part of the bug report.

GIVEN a user is presented with an empty staking form
WHEN a user clicks into an input box for a required field
AND they click out of the input box
THEN they are presented with a validation error

☝️ This is expected behavior because both the validator and amount are required fields!

Let's look at the rest of the bug report...

GIVEN a user is presented with a staking form with validation errors because of missing required fields
WHEN a user clicks "add stake" or "remove stake"
THEN they should see the validator ID field populated
AND they should see the amount field cleared
**AND they should see the validation warnings cleared**

☝️ here is where the bug occurs. How can we write a solution that clears the form's validation when the user clicks "add stake" or "remove stake"?

2022-03-07 23:15 UTC, P-v-R commented on src/views/Wallet/WalletStaking.vue
> +              :validateOnBlur="false"
@alexandreaco thanks for clearing this up. Now the `add/reduce stake` buttons will clear the form fields & corresponding error messages, assign the staking validator address and validate it, and will monitor the amount field to validate on new input. [see video and brief explanation here ](https://www.loom.com/share/5b3c8dc79f7c4f9390e984878e1e76b2)

2022-03-18 20:29 UTC, staylorwr approved these changes

2022-03-18 20:29 UTC, merged