chore: create logic to refresh app after set time and requirements
radixdlt/olympia-wallet pull request #474
Opened 2022-03-22 11:09 UTC by SK-Sam

[Demo](https://www.loom.com/share/7955a31435224ff79d669d6d859a3f51)

This PR counts mouse movement and key presses as interactions and resets application if no interactions were logged within one hour.

2022-03-22 11:28 UTC, alexandreaco approved these changes

2022-03-22 11:28 UTC, alexandreaco commented on src/background.ts
> +      win.reload()
This is a great and simple solution 🙌

2022-03-22 12:49 UTC, caleboller requested changes

2022-03-22 12:49 UTC, caleboller commented on src/background.ts
> +      win.reload()
@alexandreaco I have to disagree with your assessment here. I think there's room for improvement in this solution. 

If I'm parsing this logic correctly, this timeout operates in hour long intervals and then checks `interactionCounter` for activity in the last hour interval. What this most likely means is that our time to an actual "idle" point is quite likely longer than hour, up to 1:59:59.   For example, a user is in the middle of a 60 minute window, they stop interactions at the 30 minute mark, for that window they're considered active, it wouldn't be to the close of the next hour longer window, after 90 minutes of idle time, that they'd be recognized as idle.

I think a solution that meets the spec here would actually simplify the code a bit as well. What I've seen implemented in cases like this is a simple interval, like:

`let idleInterval = setInterval(() => { win.reload() }, 36000)`

And then for each event that would indicate an activity from a user, we'd clear that interval and recreate it, for example:

```
win.webContents.on('before-input-event', (_, input) => {
    if(input.type === 'keyDown') {
      // refactor this into its own function as we'll be calling it in multiple places
      clearInterval(idleInterval)
      idleInterval = setInterval(() => { win.reload() }, 36000)
    }
  })
```

Does that make sense?

2022-03-23 08:50 UTC, SK-Sam commented
@caleboller i've refactored based on your suggestions and it does seem simpler and handles the issue much better :) thanks https://www.loom.com/share/b840b11d338d4c738161f592908c3883

2022-03-24 20:03 UTC, saminakh reviewed
This is working for me! I left one thought in case it's helpful at all!

2022-03-24 20:03 UTC, saminakh commented on src/background.ts
> +  win.webContents.on('cursor-changed', (_, type) => {
Did we need to incorporate any debounce or throttling here? the interval will get reset a lot w/ cursor movements...are there any performance impacts that we should care about (that would be improved with the debounce/throttling)?

2022-05-03 01:20 UTC, staylorwr approved these changes

2022-05-03 15:11 UTC, caleboller approved these changes

2022-05-03 15:12 UTC, merged