work in progress
radixdlt/olympia-wallet pull request #524
Opened 2022-06-02 20:10 UTC by artsycoder533

Problem: 
- On the Unstake Tokens view, the `max` button should be disabled if the user hasnt entered an address
- Im not sure how to access the value of the address field in the template so that I can bind a disabled property to the `max` button that toggles on/off based on if this input field is empty or not.

In `WalletStaking.vue`
```
<button
  @click.prevent="setMaxUnstakeOn"
  v-if="activeForm == 'UNSTAKING'"
  class="rounded border border-rGreen text-rGreen w-2/12 h-full ml-6"
  :disabled="??????"
>
  {{ $t('staking.maxUnstakeButton') }}
</button>
```

### Before

https://user-images.githubusercontent.com/83678228/171727953-7633b982-986a-41cd-a0a8-8a99e9928d8b.mp4

### After

2022-06-08 13:24 UTC, staylorwr requested changes
Just one little style nit, everything else looks great!

2022-06-08 13:24 UTC, staylorwr commented on src/views/Wallet/WalletStaking.vue
> +                    :class="formValidatorName === '' && 'bg-rGray text-rGrayDark cursor-not-allowed border border-rGray'"
Just one style nit on the code structure, everything else is looking great!

You can use the `:class` and _object binding_ to define a conditional object of class names, it removes the dual-definition of `class`

```
                    :class="{
                      'rounded border border-rGreen text-rGreen w-2/12 h-full ml-6': true,
                      'bg-rGray text-rGrayDark cursor-not-allowed border border-rGray': formValidatorName === ''
                    }"
```

Since you're calling this `formValidatorName` twice in a few lines and it's already a computed property, you should also be able to write a new computed property to remove that duplication / be clearer with the intent:

```js
    const formValidatorName: ComputedRef<string | undefined> = computed(() => {
      if (!values.validator) return ''
      const safeAddress = safelyUnwrapValidator(values.validator)
      if (!safeAddress) return ''
      const v = maybeGetValidator(safeAddress)
      return v ? v.name : ''
    })

  const emptyValidatorName: ComputedRef<boolean> = computed(() => {
     return !!formValidatorName.value 
  })
```

```suggestion
                    :class="{
                      'rounded border border-rGreen text-rGreen w-2/12 h-full ml-6': true,
                      'bg-rGray text-rGrayDark cursor-not-allowed border border-rGray': emptyValidatorName
                    }"
```

2022-06-09 18:36 UTC, artsycoder533 commented on src/views/Wallet/WalletStaking.vue
> +                    :class="formValidatorName === '' && 'bg-rGray text-rGrayDark cursor-not-allowed border border-rGray'"
I implemented the suggested changes but I made one small change, the double bang operator inside of the `emptyValidatorName` computed property gave the opposite values than what I wanted so, I changed this to a single not and it works the same as before.

```
const emptyFormValidatorName: ComputedRef<boolean> = computed(() => {
      return !formValidatorName.value
    })
```

2022-06-09 21:12 UTC, staylorwr approved these changes

2022-06-10 12:46 UTC, merged