fix: Handle input amounts based on the selected currency format
radixdlt/olympia-wallet pull request #571
Opened 2022-08-31 18:53 UTC by staylorwr

2022-08-31 19:15 UTC, caleboller requested changes

2022-08-31 19:15 UTC, caleboller commented on src/validations.ts
> -defineRule('validAmount', (amountString: string) => {
@staylorwr Comments to clean up?

2022-08-31 19:15 UTC, caleboller commented on src/views/Wallet/WalletStaking.vue
> +    console.log(decimalType)
Console.log to remove.

2022-08-31 20:04 UTC, artsycoder533 approved these changes
Looks good to me!

2022-09-01 12:50 UTC, artsycoder533 commented on src/views/Wallet/WalletTransaction.vue
> +
Did you mean to keep the blah function? lines 330-335

2022-09-01 12:54 UTC, staylorwr commented on src/views/Wallet/WalletTransaction.vue
> +
fixed!

2022-09-01 15:37 UTC, caleboller approved these changes

2022-09-01 15:38 UTC, merged