fix: removing validator address doesn't disable 'Unstake' button
radixdlt/olympia-wallet pull request #573
Opened 2022-08-31 20:37 UTC by artsycoder533

This PR adds an onChange handler 'checkForEmptyValidator' that checks if the user changed the validator input. Previously the user could fill both the validator and amount in, then if the validator address was removed, the 'Request Unstake' button did not go back to a disabled state.  As a result, the user could click this button and nothing would happen.

[See Linear Ticket RDX-450 Here](https://linear.app/township/issue/RDX-450)

2022-08-31 21:15 UTC, staylorwr requested changes

2022-08-31 21:15 UTC, staylorwr commented on src/views/Wallet/WalletStaking.vue
> +      console.log(v, v?.name)
can you remove the console log?

2022-08-31 23:59 UTC, caleboller approved these changes

2022-09-01 12:58 UTC, staylorwr approved these changes

2022-09-01 12:59 UTC, merged